### ISSUE TITLE
java.lang.NullPointerException when scrolling

### ISSUE THREAD

**Issue by Malachiasz** [bauerca/drag-sort-listview#100]
W/dalvikvm(27335): threadid=1: thread exiting with uncaught exception (group=0x40dd5930)
FATAL EXCEPTION: main
java.lang.NullPointerException
    at com.androidquery.util.Common.shouldDelay(Common.java:328)
    at com.androidquery.util.Common.shouldDelay(Common.java:340)
    at com.androidquery.AbstractAQuery.shouldDelay(AbstractAQuery.java:2266)
    at de.meinprospekt.android.adapter.ShopsAdapter.getView(ShopsAdapter.java:76)
    at com.mobeta.android.dslv.DragSortListView$AdapterWrapper.getView(DragSortListView.java:730)
    at android.widget.AbsListView.obtainView(AbsListView.java:2159)
    at android.widget.ListView.makeAndAddView(ListView.java:1831)
    at android.widget.ListView.fillDown(ListView.java:674)
    at android.widget.ListView.fillGap(ListView.java:638)
    at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4930)
    at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4087)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
    at android.view.Choreographer.doFrame(Choreographer.java:531)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5041)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at dalvik.system.NativeStart.main(Native Method)

faulty line :  child = mAdapter.getView(position, null, DragSortListView.this);

Lets celebrate 100th issue.
Maybe it has something to do with fast scrolling enabled.

**Comment by Malachiasz** [comment]
child = mAdapter.getView(position, oldChild, DragSortListView.this);
- it doesn't get crashed when scrolling is done by fast scroll handler.

**Comment by Malachiasz** [comment]
My xml:

```
<com.mobeta.android.dslv.DragSortListView
    xmlns:dslv="http://schemas.android.com/apk/res/de.meinprospekt.android"
    android:id="@android:id/list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="0dp"
    android:choiceMode="none"
    android:dividerHeight="0px"
    dslv:collapsed_height="1px"
    dslv:drag_enabled="true"
    dslv:drag_handle_id="@id/ivDragHandle"
    dslv:drag_scroll_start="0.33"
    dslv:drag_start_mode="onDown"
    dslv:float_alpha="0.6"
    dslv:float_background_color="#27b4e7"
    dslv:remove_enabled="false"
    dslv:remove_mode="clickRemove"
    dslv:slide_shuffle_speed="0.3" />
```

But perhaps it can be closed, because it seems that error is provoked by 

aq.shouldDelay(position, convertView, parent, tbUrl)

from this library:
http://code.google.com/p/android-query/wiki/ImageLoading

Removing this line in:

" if(aq.shouldDelay(position, convertView, parent, tbUrl)){
                        aq.id(R.id.tb).image(placeholder, 0.75f);
                }else{
                        aq.id(R.id.tb).image(tbUrl, true, true, 0, 0, placeholder, 0, 0.75f);
                }
"

removes error, but then AQuery library sometimes opens too many files with images at once.
