### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by IstiN** [bauerca/drag-sort-listview#102]
Found in bugsense

java.lang.NullPointerException
at com.mobeta.android.dslv.DragSortListView.updateFloatView(DragSortListView.java:2380)
at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2321)
at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2315)
at com.mobeta.android.dslv.DragSortListView.continueDrag(DragSortListView.java:1797)
at com.mobeta.android.dslv.DragSortListView.onDragTouchEvent(DragSortListView.java:2171)
at com.mobeta.android.dslv.DragSortListView.onTouchEvent(DragSortListView.java:1635)
at android.view.View.dispatchTouchEvent(View.java:7197)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2181)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1916)
at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6882)
at android.widget.ListView.dispatchTouchEvent(ListView.java:4441)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2048)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1502)
at android.app.Dialog.dispatchTouchEvent(Dialog.java:749)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1996)
at android.view.View.dispatchPointerEvent(View.java:7391)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3559)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3488)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4602)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4581)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4673)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:184)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:131)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:5493)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
at dalvik.system.NativeStart.main(Native Method)

**Comment by widmoser** [comment]
I've got a similar one:
java.lang.NullPointerException
    at com.mobeta.android.dslv.DragSortListView.updateFloatView(DragSortListView.java:2315)
    at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2256)
    at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2250)
    at com.mobeta.android.dslv.DragSortListView.access$700(DragSortListView.java:59)
    at com.mobeta.android.dslv.DragSortListView$DropAnimator.onUpdate(DragSortListView.java:1224)
    at com.mobeta.android.dslv.DragSortListView$SmoothAnimator.run(DragSortListView.java:1131)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4898)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by cucko** [comment]
i have similar exceptions from time to time. anyone found a solution for this one?
