### ISSUE TITLE
NullPointerException in SimpleFloatViewManager (Bitmap.createBitmap)

### ISSUE THREAD

**Issue by bobbyflowstate** [bauerca/drag-sort-listview#120]
Hi there,

I'm running into the following crash.  Anyone else seeing this?  Do I need to check that v.getDrawingCache == null?

Thanks,

```
java.lang.NullPointerException
       at android.graphics.Bitmap.createBitmap(Bitmap.java:523)
       at com.mobeta.android.dslv.SimpleFloatViewManager.onCreateFloatView(SimpleFloatViewManager.java:53)
       at com.mobeta.android.dslv.DragSortListView.startDrag(DragSortListView.java:2218)
       at com.mobeta.android.dslv.DragSortController.startDrag(DragSortController.java:241)
       at com.mobeta.android.dslv.DragSortController.onScroll(DragSortController.java:411)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:560)
       at com.mobeta.android.dslv.DragSortController.onTouch(DragSortController.java:252)
       at android.view.View.dispatchTouchEvent(View.java:7271)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2168)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1903)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
```

**Comment by adouggy** [comment]
see #110
