### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by hasan5151** [bauerca/drag-sort-listview#153]
Fatal Exception: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
       at android.view.ViewGroup.addView(ViewGroup.java:4059)
       at android.view.ViewGroup.addView(ViewGroup.java:4041)
       at com.mobeta.android.dslv.DragSortListView$AdapterWrapper.getView(DragSortListView.java:739)
       at com.mobeta.android.dslv.DragSortListView.getChildHeight(DragSortListView.java:1953)
       at com.mobeta.android.dslv.DragSortListView.getItemHeight(DragSortListView.java:842)
       at com.mobeta.android.dslv.DragSortListView.updatePositions(DragSortListView.java:1001)
       at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2324)
       at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2313)
       at com.mobeta.android.dslv.DragSortListView.continueDrag(DragSortListView.java:1795)
       at com.mobeta.android.dslv.DragSortListView.onDragTouchEvent(DragSortListView.java:2169)
       at com.mobeta.android.dslv.DragSortListView.onTouchEvent(DragSortListView.java:1633)
       at android.view.View.dispatchTouchEvent(View.java:9134)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2680)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2351)
       at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5395)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2743)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3009)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2704)
       at android.view.View.dispatchPointerEvent(View.java:9344)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5042)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4880)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4482)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6938)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6811)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6782)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7028)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by jmitchell38488** [comment]
To help troubleshoot, what's the code that you're using? What's your sdk values? How are you dealing with touch? etc.

Have you overloaded any of the methods or implemented your own controller?

**Comment by Mrmarktoo** [comment]
Sorry,I tried to write a controller of my own, but without success, I used the default controller "DragSortController". You can try.
