### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by kallej** [bauerca/drag-sort-listview#2]
On my Samsung Galaxy S2 I get this exception when re-ordering items quickly. 

07-06 16:25:19.690: ERROR/AndroidRuntime(24937): FATAL EXCEPTION: main
        java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
        at java.util.ArrayList.get(ArrayList.java:304)
        at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:225)
        at com.example.DragSortListView$AdapterWrapper.getView(DragSortListView.java:233)
        at com.example.DragSortListView.getItemHeight(DragSortListView.java:333)
        at com.example.DragSortListView.getVisualItemHeight(DragSortListView.java:392)
        at com.example.DragSortListView.getDragEdge(DragSortListView.java:404)
        at com.example.DragSortListView.getFloatPosition(DragSortListView.java:461)
        at com.example.DragSortListView.access$1700(DragSortListView.java:32)
        at com.example.DragSortListView$DragScroller.run(DragSortListView.java:1356)
        at android.os.Handler.handleCallback(Handler.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:92)

Thanks for your great work on dslv!

**Comment by bauerca** [comment]
Ok thank you! I will look into this when I get back from Iceland!
Carl
On Jul 6, 2012 8:27 AM, "kallej" <
reply@reply.github.com>
wrote:

**Comment by bauerca** [comment]
would be great if you could post your fix in the meantime.

**Comment by kallej** [comment]
I thought I had a fix, but turned out I hadn't thought it through, so it didn't work after all..

**Comment by bauerca** [comment]
Do you have a header View when this crash happens?

**Comment by bauerca** [comment]
This was a bug. Found it today. Will push the change tomorrow night.

**Comment by kallej** [comment]
Hi, sorry for late reply. I don't believe I was using a headview. Glad you found a fix! Thanks!

**Comment by bauerca** [comment]
@kallej Would be great if you could try out the fix. Thanks!

**Comment by bauerca** [comment]
Shutting down 'cause I'm 94.3% sure this issue is now resolved. Thanks kallej!
