### ISSUE TITLE
ClassCastException when drawing footer

### ISSUE THREAD

**Issue by emoriarty** [bauerca/drag-sort-listview#62]
Hello, when drawing a the FooterView while dragging a list item in the listview it happens the next error:

java.lang.ClassCastException: android.view.ViewGroup$LayoutParams
at android.widget.ListView.setupChild(ListView.java:1779)
at android.widget.ListView.makeAndAddView(ListView.java:1748)
at android.widget.ListView.fillDown(ListView.java:670)
at android.widget.ListView.fillSpecific(ListView.java:1302)
at android.widget.ListView.layoutChildren(ListView.java:1588) at com.mobeta.android.dslv.DragSortListView.layoutChildren(DragSortListView.java:1974)
at com.mobeta.android.dslv.DragSortListView$DragScroller.run(DragSortListView.java:2563)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3683)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)

This problem doesn't happen if the footer was drawn, just happens when has to be drawn while dragging an item.

**Comment by bauerca** [comment]
Please let me know if that doesn't fix it.

**Comment by emoriarty** [comment]
I love you mate you saved my release, works perfectly.
Such a great library!

Cheers!
