### ISSUE TITLE
Removing Items causes ForceClose

### ISSUE THREAD

**Issue by Gadja** [bauerca/drag-sort-listview#71]
Hi,

I have a strange Problem with DragSortListView and my App.
I want to use the OnItemLongClickListener in combination with a confirmation dialog to remove Items from the list. Adding and deleting Items works quite well at startup. Drag and drop works too. But if i try to delete an item after i mixed the list with drag and drop, i get a forceclose. Do you have any Ideas?

```
package com.app.bildung;

import android.app.Activity;
import android.database.Cursor;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.AdapterView;
import android.widget.Button;
import com.mobeta.android.dslv.DragSortListView;
import com.mobeta.android.dslv.SimpleDragSortCursorAdapter;

public class MainActivity extends Activity{

    SQLiteAdapter mySQLiteAdapter;
    SimpleDragSortCursorAdapter cursorAdapter;
    static Cursor cursor;
    Button exampleButton;
    DragSortListView dropList;
    int deleteID;
    int chng = 0;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);    

        setContentView(R.layout.list);
        exampleButton = (Button) findViewById(R.id.add);
        dropList  = (DragSortListView) findViewById(R.id.contentlist);

        mySQLiteAdapter = new SQLiteAdapter(MainActivity.this);
        mySQLiteAdapter.openToWrite();
        cursor = mySQLiteAdapter.queueAll();
        cursor.moveToFirst();

        String[] from = new String[]{SQLiteAdapter.KEY_ID, SQLiteAdapter.KEY_CONTENT1, SQLiteAdapter.KEY_CONTENT2};
        int[] to = new int[]{R.id.id, R.id.text1, R.id.text2};

        cursorAdapter =new SimpleDragSortCursorAdapter(MainActivity.this, R.layout.test, cursor, from, to, 0);
        dropList.setAdapter(cursorAdapter);



        //This button adds some example items to the listview

        exampleButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View arg0) {

                String text1 = "";
                String text2 = "";

                if(chng==0){
                    text1 = "AAAAAA";
                    text2= "111111";
                    chng =1;
                }else if(chng==1){
                    text1= "BBBBBB";
                    text2= "222222";
                    chng =2;
                }else if(chng==2){
                    text1= "CCCCCC";
                    text2= "333333";
                    chng =0;
                }


                mySQLiteAdapter.insert(text1, text2);                   
                cursor.requery();
                cursorAdapter.notifyDataSetChanged();                    
            }
        });




        //onItemLongClick deletes items in the listview

        dropList.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {


                Cursor cursor2 = (Cursor) parent.getItemAtPosition(position);
                deleteID = cursor2.getInt(cursor.getColumnIndex(SQLiteAdapter.KEY_ID));


                mySQLiteAdapter.delete_byID(deleteID);  
                cursor.requery();                   
                cursorAdapter.notifyDataSetChanged();

                return true;
            }
        });

    }



    @Override
    protected void onDestroy() {
        super.onDestroy();
        mySQLiteAdapter.close();
    }


} 
```

Log: 

``````
01-30 18:41:37.418: D/AndroidRuntime(31379): Shutting down VM
01-30 18:41:37.418: W/dalvikvm(31379): threadid=1: thread exiting with uncaught exception (group=0x41ffa300)
01-30 18:41:37.434: E/AndroidRuntime(31379): FATAL EXCEPTION: main
01-30 18:41:37.434: E/AndroidRuntime(31379): java.lang.IllegalStateException: couldn't move cursor to position 2
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:248)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at com.mobeta.android.dslv.DragSortCursorAdapter.getView(DragSortCursorAdapter.java:104)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at com.mobeta.android.dslv.DragSortListView$AdapterWrapper.getView(DragSortListView.java:659)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.AbsListView.obtainView(AbsListView.java:2269)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.ListView.makeAndAddView(ListView.java:1769)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.ListView.fillDown(ListView.java:672)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.ListView.fillSpecific(ListView.java:1330)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.ListView.layoutChildren(ListView.java:1600)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at com.mobeta.android.dslv.DragSortListView.layoutChildren(DragSortListView.java:1982)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.AbsListView.onLayout(AbsListView.java:2120)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.View.layout(View.java:13767)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewGroup.layout(ViewGroup.java:4364)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.View.layout(View.java:13767)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewGroup.layout(ViewGroup.java:4364)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.View.layout(View.java:13767)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewGroup.layout(ViewGroup.java:4364)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.View.layout(View.java:13767)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewGroup.layout(ViewGroup.java:4364)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.View.layout(View.java:13767)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewGroup.layout(ViewGroup.java:4364)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1873)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1694)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1005)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4242)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.Choreographer.doFrame(Choreographer.java:525)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.os.Handler.handleCallback(Handler.java:615)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.os.Handler.dispatchMessage(Handler.java:92)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.os.Looper.loop(Looper.java:137)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at android.app.ActivityThread.main(ActivityThread.java:4758)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at java.lang.reflect.Method.invokeNative(Native Method)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at java.lang.reflect.Method.invoke(Method.java:511)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
01-30 18:41:37.434: E/AndroidRuntime(31379):    at dalvik.system.NativeStart.main(Native Method)```
``````

**Comment by Gadja** [comment]
i found a workaround. i used ArrayList instead of cursor. It is much more simple and worked for me. btw dslv is fantastic. Keep up the good work!
